// Shungen All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace BluehorseGameplayTags
{
	//--- Input Tags ---//
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Block);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SubWeaponSkill);
	//BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Parry);
	//BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_FlashSlash);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Sword);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Sword);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Nodachi);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Nodachi);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Sword);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Sword);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ultimate);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UsePotion);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UseItem);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SelectItem);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);

	//--- Item Tags ---//
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Potion);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Aether);

	//--- Player Tags ---//
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Move);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Look);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Nodachi);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Nodachi);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Interact);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UsePotion);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_UseItem);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SelectItem);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Light);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Light_1);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Light_2);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Light_3);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Light_4);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Heavy);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Heavy_1);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Heavy_2);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Heavy_3);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Sword_Heavy_4);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Nodachi_Light);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Nodachi_Light_1);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Nodachi_Light_2);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Nodachi_Heavy);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Nodachi_Heavy_1);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Nodachi_Heavy_2);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll_Combat);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll_NotCombat);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_MustBeHeld);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Skill_Parry);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Skill_Slash);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Skill_FlashSlash);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Ultimate);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Victory);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Shield);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Nodachi);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Sword);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Sword);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Shield);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Shield);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Nodachi);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Nodachi);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulParry);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulHajiki);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Combo_PreInput);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Combo_NextAttack);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Victory);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Combat);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Parrying);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Invincible);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Hajiki);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_NoCancel);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	//--- Enemy Tags ---//
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Type_Minion);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Type_Boss);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Knockdown);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon_Sword);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_Knockdown);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_TurnToTarget_Begin);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_TurnToTarget_End);

	//--- Shared Tags ---//
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Knockdown);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Executed);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_Executed);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnAOE);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Knockdown);

	//--- Game Data Tags ---//
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_WaitingAreaMap);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_CombatGameModeMap);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_BossMap);
	BLUEHORSE_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameData_Level_TitleMap);
}